title: Linear
author: Linear
email: linear.sldk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  일기, 독서 기록, 이것저것의 아카이빙
url: "https://linearlog.com"
logo: /assets/profile.jpg
theme: minima

postype:
  username: linear

plugins:
- jekyll-seo-tag

# Build settings
plugins_dir : ./_plugins_dev
