title: Linear
author: Linear
email: seonyeong.linear@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  일기, 독서 기록, 이것저것의 아카이빙
url: "https://linearlog.com"
logo: /assets/profile.jpg
theme: minima

postype:
  username: linear
google_analytics: G-SQE6M9YXWY

plugins:
- jekyll-seo-tag
- jekyll-sitemap