title: Linear
author: Linear
email: linear.sldk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  오늘도 도전한다 블로그 대통합
url: "https://linearlog.com"
image: "/assets/profile.jpg"
theme: minima

postype:
  username: linear
mastodon:
- username: linear
  instance: uri.life
twitter:
  username: linear_crv
  card: summary

plugins:
- jekyll-seo-tag

# Build settings
plugins_dir : ./_plugins_dev
